{
 "title": "Fuse Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average performance of Flight Operators",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{context='AirportsSOAPQuery', type='context'}"
    }
   ]
  },
  {
   "title": "Min Processing time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "org_apache_camel_MinProcessingTime{context=\"AirportsSOAPQuery\",service=\"flightoperators\",type=\"context\"}"
    },
    {}
   ]
  },
  {
   "title": "Max Processing time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "org_apache_camel_MaxProcessingTime{context=\"AirportsSOAPQuery\",type=\"context\"}\t"
    }
   ]
  },
  {
   "title": "Last response time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "org_apache_camel_LastProcessingTime{context=\"AirportsSOAPQuery\",type=\"routes\", route='\"OperatorQuery\"'}"
    }
   ]
  },
  {
   "title": "Fuse Online Failures",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesFailed{context=\"OperatorService\",deployment=\"i-operatorservice-1\",deploymentconfig=\"i-operatorservice\",instance=\"10.1.7.136:9779\",job=\"integration-pods\",kubernetes_namespace=\"fuse-online\",kubernetes_pod_name=\"i-operatorservice-1-9lcwh\",syndesis_io_app=\"syndesis\",syndesis_io_component=\"integration\",syndesis_io_deployment_version=\"1\",syndesis_io_integration=\"i-operatorservice\",syndesis_io_integration_id=\"i-L_8H3kcEnv8QPS4Gm1mz\",syndesis_io_integration_name=\"OperatorService\",syndesis_io_type=\"integration\",syndesis_io_username=\"user10\",type=\"context\"}"
    }
   ]
  },
  {
   "title": "Last Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_LastProcessingTime{context=\"AirportsSOAPQuery\",type=\"routes\", route='\"OperatorQuery\"'}"
    }
   ]
  },
  {
   "title": "Flight Operator SOAP requests completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesCompleted{context=\"AirportsSOAPQuery\",route='\"RoutetoCorrectSOAPOperation\"',type=\"routes\"}"
    }
   ]
  },
  {
   "title": "Failed SOAP Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesFailed{context=\"AirportsSOAPQuery\",type=\"context\"}"
    }
   ]
  },
  {
   "title": "Fuse Online Integration Service requests completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesTotal{context=\"OperatorService\",deployment=\"i-operatorservice-1\",deploymentconfig=\"i-operatorservice\",instance=\"10.1.7.136:9779\",job=\"integration-pods\",kubernetes_namespace=\"fuse-online\",kubernetes_pod_name=\"i-operatorservice-1-9lcwh\",syndesis_io_app=\"syndesis\",syndesis_io_component=\"integration\",syndesis_io_deployment_version=\"1\",syndesis_io_integration=\"i-operatorservice\",syndesis_io_integration_id=\"i-L_8H3kcEnv8QPS4Gm1mz\",syndesis_io_integration_name=\"OperatorService\",syndesis_io_type=\"integration\",syndesis_io_username=\"user10\",type=\"context\"}"
    }
   ]
  },
  {
   "title": "JVM Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"flightoperators\",namespace=\"daa-demo-project\", service=\"flightoperators\"}"
    }
   ]
  }
 ]
}