
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package operators;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5.redhat-00001
 * 2019-02-28T16:42:47.312Z
 * Generated source version: 3.2.5.redhat-00001
 *
 */

@javax.jws.WebService(
                      serviceName = "OperatorsServiceService",
                      portName = "OperatorsServicePort",
                      targetNamespace = "http://operators/",
                      wsdlLocation = "file:/Users/pprosser/git/airports/airports/src/main/resources/airports.wsdl",
                      endpointInterface = "operators.OperatorsService")

public class OperatorsServicePortImpl implements OperatorsService {

    private static final Logger LOG = Logger.getLogger(OperatorsServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see operators.OperatorsService#operatorQuery()*
     */
    public java.util.List<operators.OperatorType> operatorQuery() {
        LOG.info("Executing operation operatorQuery");
        try {
            java.util.List<operators.OperatorType> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
