package operators;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5.redhat-00001
 * 2019-02-28T16:42:47.356Z
 * Generated source version: 3.2.5.redhat-00001
 *
 */
@WebService(targetNamespace = "http://operators/", name = "OperatorsService")
@XmlSeeAlso({ObjectFactory.class})
public interface OperatorsService {

    @WebMethod(action = "http://localhost:8080/cxf/airports/operatorQuery")
    @RequestWrapper(localName = "operatorQuery", targetNamespace = "http://operators/", className = "operators.OperatorQuery")
    @ResponseWrapper(localName = "operatorQueryResponse", targetNamespace = "http://operators/", className = "operators.OperatorQueryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<operators.OperatorType> operatorQuery();
}
